//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : FileType.h
//  @ Date : 3/21/2015
//  @ Author : 
//
//


#if !defined(_FILETYPE_H)
#define _FILETYPE_H


enum FileType {
};

#endif  //_FILETYPE_H
