//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : FileCategory.h
//  @ Date : 3/21/2015
//  @ Author : 
//
//


#if !defined(_FILECATEGORY_H)
#define _FILECATEGORY_H


enum FileCategory {
};

#endif  //_FILECATEGORY_H
